name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04
    #runs-on: windows-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
         submodules: recursive

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: |
          cd LiveVideo10ms
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd LiveVideo10ms
          ./gradlew build